<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="0">

  <testsuite name="before"
    errors="1" failures="0" hostname="" id="" package="before" skipped="0"
    tests="0" time="0.000" timestamp="Mon, 24 Jul 2017 05:58:49 GMT">
  

  
    <system-err>
      Error: Provided error before
    at Object.before (/Users/Sneha/Documents/nightwatch-0.9.16/test/asynchookstests/async-provide-error/before.js:9:10)
    at TestSuite.runHookMethod (/Users/Sneha/Documents/nightwatch-0.9.16/lib/runner/testsuite.js:591:17)
    at TestSuite.&lt;anonymous&gt; (/Users/Sneha/Documents/nightwatch-0.9.16/lib/runner/testsuite.js:105:16)
    at TestSuite.makePromise (/Users/Sneha/Documents/nightwatch-0.9.16/lib/runner/testsuite.js:528:8)
    at Object.before (/Users/Sneha/Documents/nightwatch-0.9.16/lib/runner/testsuite.js:84:21)
    at TestSuite.before (/Users/Sneha/Documents/nightwatch-0.9.16/lib/runner/testsuite.js:426:21)
    at TestSuite.runTestSuiteModule (/Users/Sneha/Documents/nightwatch-0.9.16/lib/runner/testsuite.js:313:15)
    at /Users/Sneha/Documents/nightwatch-0.9.16/lib/runner/testsuite.js:227:21
    at _fulfilled (/Users/Sneha/Documents/nightwatch-0.9.16/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/Sneha/Documents/nightwatch-0.9.16/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/Sneha/Documents/nightwatch-0.9.16/node_modules/q/q.js:796:13)
    at /Users/Sneha/Documents/nightwatch-0.9.16/node_modules/q/q.js:556:49
    at runSingle (/Users/Sneha/Documents/nightwatch-0.9.16/node_modules/q/q.js:137:13)
    at flush (/Users/Sneha/Documents/nightwatch-0.9.16/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    </system-err>
  

  
  </testsuite>
</testsuites>
